### ISSUE TITLE
Readme übersetzen

### ISSUE THREAD

**Issue by RobinDobra** [Elge/BA-Matching#14]
Englische Texte im Repository (zusätzlich) auf Deutsch übersetzen

**Comment by Elge** [comment]
Bitte nochmal ordentlich machen:

- Die Formattierung der englischen Version kann man übernehmen: Code Blöcke, Unteraufzählung 
- Wenn du die englische Version drin lässt, bitte am Anfang des Dokuments ein kleines "English version see below" und den Wechsel der Sprache mit einer Überschrift ankündigen.
