### ISSUE TITLE
"Profil veröffentlichen" Checkbox ist in diversen Browsern nicht ordentlich formatiert

### ISSUE THREAD

**Issue by Elge** [Elge/BA-Matching#21]
Unter einigen Browsern und Betriebssystemen sieht die Checkbox "Profil veröffentlichen" im "Profil bearbeiten" nicht so aus, wie die Referenzansicht unter Windows und Chrome.

macOS 10.14.5 Firefox 60.7.2
<img width="336" alt="macOS_10 14 5-Firefox_60 7 2" src="https://user-images.githubusercontent.com/7862596/60864361-a78b7380-a223-11e9-8a44-fedd39ca7c59.png">

macOS 10.14.5 Chrome 75.0.3770.100
<img width="361" alt="macOS_10 14 5-Chrome_75 0 3770 100" src="https://user-images.githubusercontent.com/7862596/60864224-46fc3680-a223-11e9-8737-5b743dc22e16.png">

**Comment by RobinDobra** [comment]
ToDo: Screenshots

**Comment by RobinDobra** [comment]
Chrome, Windows 10:
![image](https://user-images.githubusercontent.com/38532066/63500496-3ef21080-c4ca-11e9-8ddd-aff849482279.png)

**Comment by Elge** [comment]
@NicoleSch Schaust du mal, ob du noch Browser/OS-Kombinationen hast, die Robin nicht abgedeckt hat?

**Comment by NicoleSch** [comment]
![Bildschirmfoto vom 2019-08-23 19-16-49](https://user-images.githubusercontent.com/46785242/63610968-13128000-c5db-11e9-81a8-2cc8652c490d.png)
Linux Mint, Firefox
