### ISSUE TITLE
Zugriff auf Seiten eingrenzen

### ISSUE THREAD

**Issue by Elge** [Elge/BA-Matching#22]
Wenn der Benutzer keine Zugriffsrechte auf die Funktionen hat, darf er auch keine Zugriffsrechte auf die Seite haben.

Lösungsvorschlag: Router konfigurieren, dass er gar nicht auf die Seite kommt.

**Comment by NicoleSch** [comment]
Warten auf merge von #1, um für Kontaktformular Router config zu implementieren
