### ISSUE TITLE
Konzept erstellen "Kontaktanfrage loggen"

### ISSUE THREAD

**Issue by Elge** [Elge/BA-Matching#48]
Es muss ein Konzept erstellt werden, wie die Kontaktaufnahme geloggt werden soll. Diese Daten können wir nämlich vermutlich nicht in Google Analytics einbringen.

- Die Kontaktanfragen müssen in der Datenbank verzeichnet werden.
- Es muss für Administratoren die Möglichkeit geben, die Kontaktanfragen einzusehen.
  - Die Kontaktanfragen, die ein Praxispartner gesendet hat.
  - Die Kontaktanfragen, die ein Bewerber bekommen hat.
  - Der Text sollte vielleicht auch einsehbar sein? Das muss geklärt werden, ob das ok geht.

**Comment by RobinDobra** [comment]
"Diese Daten können wir nämlich vermutlich nicht in Google Analytics einbringen." - Aus Datenschutzgründen oder wieso genau?

"Die Kontaktanfragen müssen in der Datenbank verzeichnet werden." - Meinst du damit den Inhalt, die Metadaten oder beides?

**Comment by Elge** [comment]
> "Diese Daten können wir nämlich vermutlich nicht in Google Analytics einbringen." - Aus Datenschutzgründen oder wieso genau?
Meiner Erfahrung nach erfasst GA sehr ungerne detailierte Daten, die sich zu einer einzelnen Sitzung zurückverfolgen lassen. Außerdem hätte ich das Log gerne auch, wenn jemand die Domain blockiert hat. ^^
> "Die Kontaktanfragen müssen in der Datenbank verzeichnet werden." - Meinst du damit den Inhalt, die Metadaten oder beides?
Alle nötigen Daten, um die Kontaktanfrage wiederstellen zu können.

**Comment by RobinDobra** [comment]
Achso das ist natürlich ungünstig^^

Okay dann wohl alles :P
