### ISSUE TITLE
Besprechung Zwischenstand mit Frau Brauer

### ISSUE THREAD

**Issue by RobinDobra** [Elge/BA-Matching#56]
Einen Privattermin mit Frau Brauer vereinbaren, um den aktuellen Stand abzugleichen und gegebenenfalls Missverständnisse zu beseitigen.

**Comment by Elge** [comment]
Zu klären:

- Nochmal deutlich machen, dass wir nichts mit der Warteliste zu tun haben. Wir haben dann lediglich irgendwo in der Administration eine Checkbox, in der "Kurs voll ja/nein" angeklickt wird. Der Wert "ja" führt dann zu einer Warnung irgendwo (wo genau?): "Bitte beachten Sie, dass der Kurs ausgebucht ist. Weitere Bewerber werden auf der Warteliste platziert. Sie können trotzdem Kontakt mit dem Bewerber aufnehmen./Sie können trotzdem ihr Interesse an dem Studiengang eintragen."
