### ISSUE TITLE
Kontaktanfragen Log: API Endpoint implementieren

### ISSUE THREAD

**Issue by Elge** [Elge/BA-Matching#65]
Gemäß der API Spezifikation aus #64 muss der entsprechende API Endpunkt implementiert werden. Der Zugriff auf diese API darf nur für Admins erlaubt sein!

**Comment by NicoleSch** [comment]
Warte mit Abarbeitung auf Abnahme des Tickets #67 (41?), da dort Tabelle zu Kontaktanfragen definiert ist
