### ISSUE TITLE
Internet Explorer, Windows 10: generierte Registrierungscodes werden nicht angezeigt

### ISSUE THREAD

**Issue by RobinDobra** [Elge/BA-Matching#76]
![image](https://user-images.githubusercontent.com/38532066/63508009-584e8900-c4d9-11e9-8e31-ff651bf90f06.png)

Die Registrierungscodes werden sauber generiert, allerdings werden sie im Internet Explorer nicht angezeigt (in Chrome und Firefox allerdings schon).

**Comment by NicoleSch** [comment]
Fehler nicht mehr reproduzierbar (Gelöst durch Zufall?)
