### ISSUE TITLE
Bewerberliste: Kontaktdaten und persönliche Daten der Bewerber aus Frontend und API entfernen

### ISSUE THREAD

**Issue by RobinDobra** [Elge/BA-Matching#8]
Die Praxispartner sollen nur noch eine Liste an anonymisierten Bewerbern sehen. Das heißt, es sind nur die Kurse, die Beschreibung und eventuell die Daten aus Issue #10 zu sehen.

**Comment by RobinDobra** [comment]
Es soll essenziell nur noch Beschreibung und Kurse verbleiben.

**Comment by Elge** [comment]
Die Administratoren sollen allerdings weiterhin alle Daten sehen können. Daher Bewerberliste aus Praxispartnersicht als neue Komponente implementieren.

**Comment by Elge** [comment]
@NicoleSch Schaust du mal drüber, ob das so in Ordnung geht? Ist im Branch 8_remove_personal_data

**Comment by NicoleSch** [comment]
@Elge Wollen wir für die Review einen Pullrequest erstellen?
